# -*- coding: utf-8 -*-
"""volume_of_sphere.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q8i-tuZdFwKRnF-z1xDcrcEjaaaokMIg
"""

import math

def calculate_volume_of_sphere(radius):
    return (4/3) * math.pi * (radius ** 3)

# Compute and print volumes for radii 30 and 40
volume_30 = calculate_volume_of_sphere(30)
volume_40 = calculate_volume_of_sphere(40)

print("Volume of sphere with radius 30:", volume_30)
print("Volume of sphere with radius 40:", volume_40)
