# -*- coding: utf-8 -*-
"""volume_of_sphere.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q8i-tuZdFwKRnF-z1xDcrcEjaaaokMIg
"""

import math

def calculate_volume_of_sphere(radius):
    return (4/3) * math.pi * (radius ** 3)

# Ask user for input and print result
r = float(input("Plz enter the radius of the sphere "))
volume = calculate_volume_of_sphere(r)
print("The volume of the sphere is ", round(volume, 2))